name: Build

on: push

jobs:
  build1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # todo whats this

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.15.0'

      - run: npm install
      - run: npm test

  build2:
      runs-on: ubuntu-latest
      needs: build1
      if: ${{ needs.build1.outputs.result == 'success' }}
      steps:
        - name: step in job2
          run: echo "Printing this because job1 was successful"
  
  