name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # todo whats this

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.15.0'

      # - run: npm install
      - run: npm test
  
  